### ISSUE TITLE
Hardware Requirement

### ISSUE THREAD

**Issue by EmreOzkose** [JuanFMontesinos/Acappella-YNet#4]
Hi,

What is hardware requirements? How many GPUs did you use?

**Comment by JuanFMontesinos** [comment]
A single GPU either Quaddro P6000 or a RTX 3090
Yet should be trainable with 12 Gb GPUs

**Comment by EmreOzkose** [comment]
@JuanFMontesinos how many days did you train ?

**Comment by JuanFMontesinos** [comment]
I think it was about 12 days. At day 7 you can start getting good results
