### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by EmreOzkose** [JuanFMontesinos/Acappella-YNet#5]
Hi,

I run `run.py` and it gives me some metrics like sdr/ds, etc.. Are these metrics equal to ones without `ds`? I search `ds` term in code, but couldn't find what it is exactly. For example I got `sdr/ds=13.4` for my training, can I say sdr=13.4 ?

**Comment by JuanFMontesinos** [comment]
Hi, 
You can find the implementation of sdr at
https://github.com/JuanFMontesinos/Acappella-YNet/blob/main/VnBSS/trainer.py

The -ds too

It's just for tensorboard to group the parameters in a certain way. So yes, that's sdr for the validation set.

In theory if you are using traces for the validation set, that metric should run on exactly the same pair samples.

**Comment by EmreOzkose** [comment]
Thank you :)
