### ISSUE TITLE
There was a problem when I was executing on Colab,

### ISSUE THREAD

**Issue by 110wuqu** [JuanFMontesinos/Acappella-YNet#6]
state_dict = load(path, map_location=lambda storage, loc: storage)

UnpicklingError: invalid load key, '<'.

**Comment by JuanFMontesinos** [comment]
Hi, my guess is it's all about the new pytorch version (1.11) as this was coded ffor 1.10
I will have a look at it

**Comment by JuanFMontesinos** [comment]
Hi,
It's fixed now. It seems GoogleDriveDownloader is no longer maintained and I replaced that by gdown. Also sticked to pytorch 1.10
